namespace backend.Exceptions
{
    public enum ErrorCode
    {
        ParentFolderNotFound,
        FolderNotFound,
        FolderNameConflict,
        WorkNotFound,
        ColorNotFound,
        ColorNameConflict,
        EmailAlreadyExists,
        InvalidCredentials,
        InvalidRefreshToken,
        InvalidOrExpiredCode,
        PendingRegistrationNotFound,
        PatternNotFound,
        PatternAlreadyExists,
        PatternOutOfBounds,
        WorkNotPatternType,
        PatternTooLarge,
        PatternTooSmall,
        VideoLinkRequired,
        VideoLinkNotSupported,
        VideoLinkNotWorking,
        VideoNotFound,
        SiteLinkInvalid,
        SiteNotFound,
        CommentNotFound,
        CommentEmpty,
        CommentTooLong,
    }
}
